name = "ob-poll"
compatibility_date = "2026-01-29"

assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "ob-poll"
database_id = "ca58cede-c2a2-49ac-a43d-e2ca9740a2d8"
migrations_dir = "migrations"
